#@package _global_
defaults:
  - /prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: step
  - /datamodule: ph14
  - /transforms/train: 224x224
  - /transforms/test: 224x224
  - /model: resnet_attn_v2
  - /loss: heatmapfocalresnet

seed: 3407
epoch: 200
tags:
  - heatmap
  - dwpose
  - resnet_attn_v2

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt

# data_excluded: ["13April_2011_Wednesday_tagesschau_default-14"]
data_excluded: []

datamodule:
  batch_size: 2
  num_workers: 6
  train_shuffle: False

loss:
  weights: [1, 100.0] # ctc loss, heatmap loss
  sigmas: [1., 1., 1.]
  num_stages: 3
  gamma: 2

optimizer:
  lr: 1e-4

lr_scheduler:
  step_size: 40
  gamma: 0.1
