#@package _global_
defaults:
  - /prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: step
  - /datamodule: ph14
  - /transforms/train: 224x224dwpose
  - /transforms/test: 224x224dwpose
  - /model: heatmap_mask
  - /loss: heatmap
 
seed: 3407
epoch: 200
tags: 
  - heatmap
  - dwpose

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
datamodule:
  batch_size: 2
  num_workers: 6
  train_shuffle: False
    
loss:
  weights: [0, 100.0] # ctc loss, heatmap loss
  sigmas: [2, 1.5, 1.2, 1.0, 0.8] # sigma for each stage
  # stage_lambda: [1.0, 1.0, 1.0, 1.0, 1.0] # lambda for each stage
  stage_lambda: [0., 0., 0., 0., 1.0] # lambda for each stage


optimizer:
  lr: 1e-8

lr_scheduler:
  step_size: 20
  gamma: 0.1
