#@package _global_
defaults:
  - /prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: step
  - /datamodule: ph14
  - /transforms/train: 224x224
  - /transforms/test: 224x224
  - /model: resnet_distill_v2_efficient_decoder
  - /loss: multitask_distill_v2

seed: 3407
epoch: 200
tags:
  - multitask_distill_v2
  - dwpose
  - vitpose
  - resnet
  - sparse_attention

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt
devices: [0, 1]

datamodule:
  batch_size: 1
  num_workers: 4
  train_shuffle: False

optimizer:
  lr: 1e-4

lr_scheduler:
  step_size: 40
  gamma: 0.1
