#@package _global_
defaults:
  - /prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: step
  - /datamodule: ph14
  - /transforms/train: 192x192
  - /transforms/test: 192x192
  - /model: resnet_trans
  - /loss: vac
  
seed: 3407
epoch: 200
tags: 
  - resnet_trans

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
datamodule:
  batch_size: 1
  num_workers: 6
  train_shuffle: False


optimizer:
  lr: 1e-4

lr_scheduler:
  step_size: 40
  gamma: 0.1
