#@package _global_
defaults:
  - /prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: step
  - /datamodule: ph14
  - /transforms/train: 224x224vifi_clip
  - /transforms/test: 224x224vifi_clip 
  - /model: vifi_clip
  - /loss: vac
  
seed: 3407
epoch: 200
tags: 
  - vifi_clip

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
datamodule:
  batch_size: 2
  num_workers: 6
  train_shuffle: False

#loss
loss:
  weights: [1., 0., 0.]

optimizer:
  lr: 1e-5

lr_scheduler:
  step_size: 40
  gamma: 0.1
