#@package _global_
defaults:
  - /prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: step
  - /datamodule: ph14
  - /transforms/train: 224x224dwpose
  - /transforms/test: 224x224dwpose
  - /model: vit_with_attn
  - /loss: heatmapfocal

seed: 3407
epoch: 200
tags: 
  - vit
  - focal_loss
  - dwpose

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
datamodule:
  batch_size: 2
  num_workers: 6
  train_shuffle: False
    
loss:
  weights: [1.0, 0.] # ctc loss, heatmap loss
  sigmas: [2, 1.5, 1.2, 1, 0.8]
  stages: [7, 8, 9, 10, 11]


optimizer:
  lr: 1e-5

lr_scheduler:
  step_size: 20
  gamma: 0.1
