#@package _global_
defaults:
  - /_global_/prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /engines: defaults
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /datamodule: ph14
  - /transforms/train: 192x192
  - /transforms/test: 192x192
  - /model: vitpose_vitpool_tconv_convformer
  - /loss: vac
  
seed: 3407
device: cuda
epoch: 80
  
snap_path: snap

#-1 when we don want message out
message_interval: 100
vocab_size: 1296

#if continuos read model
load_weights: False
is_resume: False
checkpoint: /home/jingyan/Documents/sign_language_rgb/outputs/train_ddp/2024-04-08_19-50-22/checkpoint.pt
  

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
datamodule:
  batch_size: 1
  num_workers: 6
  train_shuffle: False

optimizer:
  lr: 1e-3

lr_scheduler:  
  milestones: [20, 40, 55, 65, 75, 80, 85, 90]
  gamma: 0.5

# lr_scheduler:  
#   milestones: [100]
#   gamma: 0.5
