#@package _global_
defaults:
  - /prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /datamodule: ph14
  - /transforms/train: 192x192
  - /transforms/test: 192x192
  - /model: vitpose_tconv_trans
  - /loss: vac
  
seed: 3407
epoch: 100
tags: 
  - vitpose_tconv_trans
  - pytorch_lightning

#if continuos read model
load_weights: True
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
datamodule:
  batch_size: 1
  num_workers: 6
  train_shuffle: False

optimizer:
  lr: 1e-7

lr_scheduler:  
  milestones: [40, 80]
  gamma: 0.5

# optimizer:
#   lr: 1e-4

# lr_scheduler:
#   milestones:
#   - 20
#   - 40
#   - 55
#   - 65
#   - 75
#   - 80
#   - 85
#   - 90
#   gamma: 0.5