
_target_: ${csi}.modules.clip_adapters.model.ClipAdapter
n_class: 1296
clip_model: ViT-B-16
pretrained: openai
img_size: [224, 224]
adapter_spec:
  position: [2, 4, 6, 8, 10, 12]
  type: [L, L, L, G, G, G]
  drop_path: [0., 0., 0. ,0. ,0., 0.]
pooling_spec: [0, 6]