_target_: ${csi}.modules.base_stream.BaseStream
encoder:
  _target_: ${csi}.modules.ResnetFocalEncoderV2
  arch: resnet-18
  ckpt: resources/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
  focal_module_cfg:
    embed_dims: [128, 256, 512]
    heads: [8, 8, 8]
    stage_index: [1, 2, 3]
    drop_resnet: 0.5
    drop_hand: 0.5
    dropout_face: 0.5
decoder:
  _target_: ${csi}.modules.EfficientDecoder
  input_dims: 512
  d_model: 1024
  n_layers: 8
  n_head: 8
  n_classes: 1296
  bucket_size: 4
  conv_kernel_head: 5
  conv_kernel_block: 3
  ff_dropout: 0.0
  drop_path: 0.0
