_target_: ${csi}.modules.slr_base.base_stream.BaseStream
encoder: 
  _target_: ${csi}.modules.slr_base.pose_rgb_encoder.SwinPoseEncoder
  swin_cfg: ${swin_cfg}
  swin_ckpt: ${swin_ckpt}
  num_keypoints: 17
  drop_path_rate: 0.5
  pose_embd_dims: 96
neck:
  _target_: ${csi}.modules.tconv.TemporalConv1D
  input_size: 512
  out_size: 512
  bottleneck_size:  256
  conv_type: ['K5', 'P2', 'K5', 'P2']
decoder:
  _target_: ${csi}.modules.slr_base.decoders.TransformerDecoder
  n_class: 1296
  d_model: 512
  n_heads: 8
  n_layers: 6
  d_feedforward: 1024
  dropout: 0.5