_target_: ${csi}.modules.base_stream.BaseStream
encoder: 
  _target_: ${csi}.modules.encoders.swin_encoder.SwinEncoder
  cfg: ${swin_cfg}
  ckpt: ${swin_ckpt}
neck:
  _target_: ${csi}.modules.necks.tconv_neck.TemporalConvNeck
  in_channels: 768
  out_channels: 1024
  bottle_channels: 512
  n_class: 1296
  with_header: True,
  pooling: max
  dropout: 0.2
decoder:
  _target_: ${csi}.modules.decoders.transformer_decoder.TransformerDecoder
  n_class: 1296
  d_model: 1024
  n_heads: 8
  n_layers: 6
  d_feedforward: 2048
  dropout: 0.5