_target_: ${csi}.modules.slr_base.base_stream.BaseStream
encoder: 
  _target_: ${csi}.modules.slr_base.vitpose_encoder.VitPoseEncoder
  img_size: 192
  color_range: [0, 1]
  cfg_path: ${vitpose_cfg}
  checkpoint: ${vitpose_ckpt}
  drop_path_rate: 0.9
  freeze_vitpose: False
neck:
  _target_: ${csi}.modules.tconv.TemporalConv1D
  input_size: 384
  out_size: 1024
  bottleneck_size:  512
  conv_type: ['K5', 'P2', 'K5', 'P2']
  pooling: 'max'
decoder:
  # _target_: ${csi}.modules.slr_base.decoders.TransformerDecoder
  # n_class: 1296
  # d_model: 512
  # n_heads: 8
  # n_layers: 6
  # d_feedforward: 1024
  # dropout: 0.5
  _target_: ${csi}.modules.slr_base.conformer_decoder.ConformerDecoder
  dim: 1024
  dim_head: 64
  heads: 8
  depth: 6
  conv_kernel_size: 5
  conv_dropout: 0.1
  ff_dropout: 0.1
  n_class: 1296