_target_: ${csi}.modules.base_stream.BaseStream
encoder: 
  _target_: ${csi}.modules.encoders.vitpose_adapter_encoder.VitPoseAdapterEncoder
  color_range: [0, 1]
  cfg_path: ${vitpose_cfg}
  checkpoint: ${vitpose_ckpt}
  adapter_archs:
    stem_channel: 48
    channels: [48, 96, 192, 384]
    vit_feats_indices: [2, 5, 8, 11]
    num_heads: 8
  dropout: 0.1
neck:
  _target_: ${csi}.modules.necks.tconv_neck.TemporalConvNeck
  in_channels: 384
  out_channels: 1024
  bottle_channels: 512
  n_class: 1296
  with_header: True,
  pooling: max
  dropout: 0.2
decoder:
  _target_: ${csi}.modules.decoders.transformer_decoder.TransformerDecoder
  n_class: 1296
  d_model: 1024
  n_heads: 8
  n_layers: 6
  d_feedforward: 2048
  dropout: 0.5