_target_: ${T}.Compose
transforms: 
  #process video data
- _target_: ${CT}.common.ApplyByKey
  key: video
  transforms:
  - _target_: ${CT}.common.ToTensor
    dtype: float32
  - _target_: ${CT}.common.Rearrange
    pattern: "t h w c -> t c h w"
  - _target_: ${T}.RandomResizedCrop
    size: 224
    scale: [0.7, 1.0]
    ratio: [0.75, 1.33333333333]
    antialias: True
  - _target_: ${T}.Resize
    size: 192
    antialias: True
  - _target_: ${CT}.common.TemporalAug
    t_min: 0.5
    t_max: 1.5
    n_frame_max: 400
  - _target_: ${CT}.common.Rescale
    input: [0., 255.]
    output: [0., 1.]
  - _target_: ${CT}.t_tensor.ColorJitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.1
    p: 0.5
  #process gloss data
- _target_: ${CT}.common.ApplyByKey
  key: gloss
  transforms:
  - _target_: ${CT}.common.ToTensor
